# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: "/"
    ignore:
      - dependency-name: "github.com/confluentinc/*"
    open-pull-requests-limit: 0
    package-ecosystem: "gomod"
    schedule:
      interval: "weekly"
